### PR TITLE
opt_expr: improve single-bit $and/$or/$xor/$xnor cells; gate cells too

### LINKED ISSUE #1758: opt_expr mismatch in behaviour between $or and $_OR_ for 1'bx
## Steps to reproduce the issue

On dd8ebf787
```
read_verilog -noopt <<EOT
module top(input i, output o);
assign o = 1'bx | i;
endmodule
EOT
design -save read

opt_expr
clean; dump

design -load read
simplemap
opt_expr
clean; dump
```

## Expected behavior

Two results to be the same.

## Actual behavior

```
2. Executing OPT_EXPR pass (perform const folding).
Optimizing module top.
<suppressed ~1 debug messages>
Removed 0 unused cells and 1 unused wires.

autoidx 2

attribute \cells_not_processed 1
attribute \src "<<EOT:1.1-3.10"
module \top

  attribute \src "<<EOT:1.18-1.19"
  wire input 1 \i

  attribute \src "<<EOT:1.28-1.29"
  wire output 2 \o

  connect \o \i
end

3. Executing SIMPLEMAP pass (map simple cells to gate primitives).
Mapping top.$or$<<EOT:0$1 ($or).

4. Executing OPT_EXPR pass (perform const folding).
Optimizing module top.
<suppressed ~1 debug messages>
Removed 0 unused cells and 1 unused wires.

autoidx 3

attribute \cells_not_processed 1
attribute \src "<<EOT:1.1-3.10"
module \top

  attribute \src "<<EOT:1.18-1.19"
  wire input 1 \i

  attribute \src "<<EOT:1.28-1.29"
  wire output 2 \o

  connect \o 1'1
end
```

### PR DESCRIPTION
**Pull request by eddiehung**
Before this, `opt_expr -keepdc` wasn't always behaving correctly, and there were missed opportunities surrounding single-bit coarse cells `$and/$or/$xor/$xnor`.

Fixes #1758.

~The one remaining issue with `opt_expr` is that it won't optimise multi-bit coarse grained cells directly:~
```
read_verilog <<EOT
module top(input [1:0] i, output [1:0] o);
assign o = 2'b00 & i;
endmodule
EOT
opt_expr
```
~will show a 2-bit `$and` cell remaining. Instead, Yosys seems to rely on bit-blasting into fine-grained cells (`$_AND_`) and optimising there. I'll file this as a separate issue.~
EDIT: I'm wrong. I needed `opt_expr -fine`.

### CODE REVIEW

File: passes/opt/opt_expr.cc [hunk 1]
```diff
@@ -844,7 +858,7 @@ void replace_const_cells(RTLIL::Design *design, RTLIL::Module *module, bool cons
 			if (input.match("**")) ACTION_DO_Y(x);
 			if (input.match("1*")) ACTION_DO_Y(x);
 			if (input.match("*1")) ACTION_DO_Y(x);
-			if (consume_x) {
+			if (!keepdc) {
```
Comment (eddiehung) [inline passes/opt/opt_expr.cc:861]: @cliffordwolf I'm not sure what the significance of `consume_x` is?

File: passes/opt/opt_expr.cc [hunk 2]
```diff
@@ -148,7 +148,7 @@ bool group_cell_inputs(RTLIL::Module *module, RTLIL::Cell *cell, bool commutativ
 
 	std::vector<RTLIL::SigBit> bits_a = sig_a, bits_b = sig_b, bits_y = sig_y;
 
-	enum { GRP_DYN, GRP_CONST_A, GRP_CONST_B, GRP_CONST_AB, GRP_N };
+	enum { GRP_DYN, GRP_CONST_A, GRP_CONST_B, GRP_CONST_AB, GRP_CONST_X, GRP_N };
```
Comment (eddiehung) [inline passes/opt/opt_expr.cc:151]: Hmm. In retrospect I'm grouping by `1'bx` in order to force it to separate those "slices" out into their own (one-bit) cell so that they are optimised away in my arbitrary test cases...

File: passes/opt/opt_expr.cc (hunk 1 above)
Comment (eddiehung) [reply passes/opt/opt_expr.cc:930]: Apparently `consume_x` is part of a heuristic in `opt_expr`'s double-nested-loop that defers greedy x-consumption in case there's a better optimisation.

Comment (eddiehung) [reply passes/opt/opt_expr.cc]: Testcase that exhibits its need added in https://github.com/YosysHQ/yosys/pull/1994/commits/495acf981547850ac7ad5b765dd215b0c33d59ac -- `o == 1'b0` and `o == 1'bx` are both valid solutions, but the latter is preferable and `consume_x` enables this.

File: passes/opt/opt_expr.cc [hunk 3]
```diff
@@ -156,20 +156,36 @@ bool group_cell_inputs(RTLIL::Module *module, RTLIL::Cell *cell, bool commutativ
...
 
-		if (bit_a.wire == NULL && bit_b.wire == NULL)
-			group_idx = GRP_CONST_AB;
-		else if (bit_a.wire == NULL)
-			group_idx = GRP_CONST_A;
-		else if (bit_b.wire == NULL && commutative)
-			group_idx = GRP_CONST_A, std::swap(bit_a, bit_b);
-		else if (bit_b.wire == NULL)
-			group_idx = GRP_CONST_B;
+		bool def = (bit_a != State::Sx && bit_a != State::Sz && bit_b != State::Sx && bit_b != State::Sx);
```
Comment (Xiretza) [inline passes/opt/opt_expr.cc:178]: I think the last conditional may be intended to be `bit_b != State::Sz`?

Comment (eddiehung) [reply passes/opt/opt_expr.cc:178]: Good eye! Resolved in 7b3a4a1fff297481a463f27da250af8436041753
