### PR TITLE
Refactor and fixes to incremental bufNormalize + related changes

### LINKED ISSUE #5377: ERROR: Missing timing data for module '$input_port'.
### Version

Yosys 0.57+157 (git sha1 e546f3b8f, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3)

### On which OS did this happen?

Linux

### Reproduction Steps

Extract this tar.

[synth_gcd_nangate45_base_2025-09-23_11-16.tar.gz](https://github.com/user-attachments/files/22483334/synth_gcd_nangate45_base_2025-09-23_11-16.tar.gz)

./run-me-gcd-nangate45-base.sh

### Expected Behavior

No ERROR.

### Actual Behavior

...
ABC: <abc-temp-dir>/input : i/o =     34/     17  and =     386  lev =   16 (13.06)  mem = 0.01 MB  ch =   59  box = 0  bb = 0
ABC: + &write -n <abc-temp-dir>/output.aig 
ABC: + time 
ABC: elapse: 0.06 seconds, total: 0.06 seconds
Warning: Feature 'read_xaiger2' is experimental.

16.4.6. Executing XAIGER2 frontend.
Read 125 instances with cell library of size 30.
input file: 
input file: 
input file: This file was produced by the GIA package in ABC on Tue Sep 23 11:53:08 2025
input file: For information about AIGER format, refer to http://fmv.jku.at/aiger
<suppressed ~184 debug messages>

16.4.7. Executing ABC9_OPS pass (helper functions for ABC9).

16.5. Executing PORTARCS pass. (derive propagation arcs)
**ERROR: Missing timing data for module '$input_port'.**

### PR DESCRIPTION
**Pull request by jix**
This fixes some edge cases the rewritten bufNormalize version didn't handle properly.

This fixes #5377 and #5375. 

_Explain how this is achieved._

To made sure it handles the edge cases I previously missed by simplifying the logic of determining directly driven wires and representatives to use as buffer inputs. The `bufNormalize` code has extensive inline comments explaining the approach taken.

_If applicable, please suggest to reviewers how they can test the change._

Both #5377 and #5375 have (non-minimized but self-contained) reproducers.

Based on what I observed with them, I added a new testcase that runs `opt_clean` on a design where there is something to clean up, while staying in bufnorm mode, followed by an incremental `bufnorm -update` after `opt_clean` removed cells. Note that running arbitrary passes while manually entering bufnorm is not something we support outside of testcases like this yet. This turned out to be very effective at reproducing the bufNormalize edge cases that I encountered with the larger reproducers.

### CODE REVIEW

**Comment by jix** [comment]
The latest force push is just a rebase onto the latest main, no changes otherwise

File: kernel/rtlil_bufnorm.cc [hunk 1]
```diff
@@ -149,27 +154,14 @@ void RTLIL::Module::bufNormalize()
...
-			} else if (cell->type == ID($buf) && cell->attributes.empty() && !cell->name.isPublic()) {
+			// Make sure all wires of the cell port are enqueued, ensuring we
+			// detect other connected drivers (output and inout).
+			for (auto chunk : sig.chunks())
+				if (chunk.is_wire())
+					wire_queue_entries(chunk.wire);
+
+			if (cell->type == ID($buf) && cell->attributes.empty() && !cell->name.isPublic()) {
 				// For a plain `$buf` cell, we enqueue all wires on its input
 				// side, bypass it using module level connections (skipping 'z
```
Comment (widlarizer) [inline kernel/rtlil_bufnorm.cc:166]: I think we're enqueueing on the output side of a `$buf` as well

File: kernel/rtlil_bufnorm.cc [hunk 2]
```diff
@@ -256,16 +241,22 @@ void RTLIL::Module::bufNormalize()
 			pending_ports.emplace(cell, port);
 		};
 
+		// We enqueue all enqueued wires for `$buf`/`$connect` processing (clearing the module level queue).
```
Comment (widlarizer) [inline kernel/rtlil_bufnorm.cc:244]: I think we could have clearer distinction between the queues we're juggling in, maybe have a kind of worker struct to separate the temporary non-module-level queues?

File: kernel/rtlil_bufnorm.cc [hunk 3]
```diff
@@ -373,54 +363,55 @@ void RTLIL::Module::bufNormalize()
...
 		}
 
-		// Ensure that module level inout ports are directly driven or
-		// connected using `$connect` cells and never `$buf`fered.
-		for (auto wire : wire_queue_entries) {
-			if (!wire->port_input || !wire->port_output)
-				continue;
+		// All three pool<SigBit> below are in terms of sigmapped bits
+		// Bits that are known to have a unique driver that is an unconditional driver or one or more inout drivers
+		pool<SigBit> driven;
```
Comment (widlarizer) [inline kernel/rtlil_bufnorm.cc:381]: Are we relying on insertion ordering for these? Or just consistent ordering?

Comment (widlarizer) [inline kernel/rtlil_bufnorm.cc:381]: We could also associate these into a struct for readability

**Review by widlarizer — COMMENTED** [review]
I wasn't able to understand the whole thing so my commentary is only surface level, but I think there's a lot of potential to split up `Module::bufNormalize()` into several functions which are easier to reason about and some custom structures too

**Review by widlarizer — APPROVED** [review]

**Comment by jix** [comment]
During the dev JF, we agreed that we will merge it as-is to get the fixes for the upcoming release. This includes fixes for regressions from the previous release, that we want to avoid. The plan is to address further refactoring and cleanup for maintenance and ease of understanding in a follow up PR (see @widlarizer comments) .
