### PR TITLE
opt_expr: fix const lhs of $pow to $shl

### LINKED ISSUE #5661: Incorrect `$pow` transform by opt_expr
### Version

v0.61

### On which OS did this happen?

macOS

### Reproduction Steps

```
read_rtlil <<EOF
module \top
  wire width 3 input 2 \binary

  wire width 32 output 3 \y

  cell $pow $0
    parameter \A_WIDTH 32
    parameter \B_WIDTH 3
    parameter \A_SIGNED 1
    parameter \B_SIGNED 0
    parameter \Y_WIDTH 32
    connect \A 2
    connect \B \binary
    connect \Y \y
  end
end
EOF

dump
opt_expr
dump
```

### Expected Behavior

The transformed netlist is equivalent to the original

### Actual Behavior

```
  cell $pow $0
    parameter \A_WIDTH 32
    parameter \B_WIDTH 3
    parameter \A_SIGNED 1
    parameter \B_SIGNED 0
    parameter \Y_WIDTH 32
    connect \A 2
    connect \B \binary
    connect \Y \y
  end
```
is replaced with
```
  cell $shl $0
    parameter \A_WIDTH 1
    parameter \B_WIDTH 3
    parameter \A_SIGNED 1
    parameter \B_SIGNED 0
    parameter \Y_WIDTH 32
    connect \A 1'1
    connect \B \binary
    connect \Y \y
  end
```

Note the A input of the new instance is tied to `-1`. The function of the two netlists differs, take e.g.
```
eval -set binary 0
```
which first gives the result
```
Eval result: \y = 1.
```
and then
```
Eval result: \y = 32'11111111111111111111111111111111.
```

### PR DESCRIPTION
**Pull request by widlarizer**
Set A input signedness to unsigned in $pow -> $shl rewrite in opt_expr, even if it's a single-bit $pow. Fixes #5661. Can't prove correct with equiv since `$pow` isn't modeled with `SatGen` for computational complexity reasons, but the meaning of the change seems pretty self-evident. It's not too surprising that `$pow` cells would be mishandled due to how rarely exponentiation operators get used in real designs

### CODE REVIEW

**Comment by povik** [comment]
I propose testing by taking the setup from #5661 and then
```
opt_expr
sat -verify -set binary 0 -prove y 1
sat -verify -set binary 1 -prove y 2
sat -verify -set binary 2 -prove y 4
sat -verify -set binary 3 -prove y 8
```

File: passes/opt/opt_expr.cc [hunk 1]
```diff
@@ -1668,6 +1668,7 @@ void replace_const_cells(RTLIL::Design *design, RTLIL::Module *module, bool cons
 			const auto onehot = sig_a.is_onehot(&bit_idx);
 
 			if (onehot) {
```
Comment (povik) [inline passes/opt/opt_expr.cc]: I'm wondering if this should be `onehot && (!cell->parameters[ID::A_SIGNED].as_bool() || bit_idx < sig_a.size() - 1)`.

While putting together a reproducer I may have stumbled on an issue with how $pow are evaluated for negative A when B_SIGNED=0:
```
read_rtlil <<EOF
module \top
  wire width 3 input 2 \binary

  wire width 32 output 3 \y

  cell $pow $0
    parameter \A_WIDTH 2
    parameter \B_WIDTH 3
    parameter \A_SIGNED 1
    parameter \B_SIGNED 0
    parameter \Y_WIDTH 32
    connect \A 2'10
    connect \B \binary
    connect \Y \y
  end
end
EOF

eval -set binary 0
eval -set binary 1
eval -set binary 2
```
produces
```
2. Executing EVAL pass (evaluate the circuit given an input).
Eval result: \y = 1.

3. Executing EVAL pass (evaluate the circuit given an input).
Eval result: \y = 2.

4. Executing EVAL pass (evaluate the circuit given an input).
Eval result: \y = 4.
```
RTLIL::const_pow itself has a branch for negative A, but signed1 may be overridden before it reaches that point. simlib.v and rtlil.cc suggest A_SIGNED!=B_SIGNED is explicitly allowed on $pow.

**Review by povik — APPROVED** [review]
There may be pending issues with the case A_SIGNED=1

File: passes/opt/opt_expr.cc (hunk 1 above)
Comment (widlarizer) [reply passes/opt/opt_expr.cc]: Very good point, I changed that condition and added a test that we don't opt on negative A

Comment (povik) [reply passes/opt/opt_expr.cc]: > simlib.v and rtlil.cc suggest A_SIGNED=B_SIGNED is explicitly allowed on $pow.

Oops, this is meant to say A_SIGNED!=B_SIGNED
