### PR TITLE
iopadmap: Look harder for already-present buffers.

### LINKED ISSUE #1720: Duplicate OBUF insertion (sometimes)
## Steps to reproduce the issue

[iobuf_bug.zip](https://github.com/YosysHQ/yosys/files/4246613/iobuf_bug.zip)

1. Unzip iobuf_bug.zip
2. Run `./run.sh`
3. Run `grep "OBUF " output.v  | wc`, outputs 
```
     12      29     140
```
4. Example the stat output from circuit:
```
   Number of wires:                 23
   Number of wire bits:            146
   Number of public wires:          17
   Number of public wire bits:      50
   Number of memories:               0
   Number of memory bits:            0
   Number of processes:              0
   Number of cells:                 52
     BUFG                            1
     CARRY4                          8
     FDRE                           29
     IBUF                            1
     INV                             1
     OBUF                           12

   Estimated number of LCs:          0
```

Given that the input design only has 8 top level signals to begin with, having the final output have 12 OBUF's is pretty weird.  In this design, all 7 output signals already have OBUF's, but the iopadmap pass appears to insert some "strange" OBUF's which are not required.  It is not clear if the specification of iopadmap is intended to allow for double OBUF's, but it lowers the utility of the pass if it behaves this way.

## Expected behavior

Top level signals that lack IBUF or OBUF should gain them, but top signals that already have them should not get a second one.  What is interesting in the provided example is that there is not a straight doubling of OBUF's.  Some path's have 2 OBUF's and some still have only 1.

## Actual behavior

`iopadmap` appears sometimes add a second OBUF when there is a signal alias, for example the input:

```
module top (
  input  clk,
  output [3:0] led,
  inout out_a,
  output [1:0] out_b
);

...

wire inter_wire, inter_wire_2;
OBUF #(
  .IOSTANDARD("LVCMOS33"),
  .SLEW("SLOW")
) OBUF_7(.I(LD7), .O(inter_wire_2));
assign inter_wire = inter_wire_2;
assign led[1] = inter_wire;
```

became:

```
   (* module_not_derived = 32'd1 *)                                                
    (* src = "counter.v:25" *)                                                      
    OBUF #(                                                                         
      .IOSTANDARD("LVCMOS33"),                                                      
      .SLEW("SLOW")                                                                 
    ) OBUF_7 (                                                                      
      .I(LD7),                                                                     
      .O(inter_wire_2)                                                              
    );  
    (* keep = 32'd1 *)                                                              
    OBUF _16_ (                                                                     
      .I(inter_wire_2),                                                                                                                                                                                                                                                                   
      .O(led[1])
   );
```

Tested at `Yosys 0.9+1706 (git sha1 6edca057, clang 8.0.1-3+build1 -fPIC -Os)` which is master as of creation of this issue.

### PR DESCRIPTION
**Pull request by mwkmwkmwk**
Fixes #1720.

### CODE REVIEW

File: passes/techmap/iopadmap.cc [hunk 1]
```diff
@@ -172,22 +186,49 @@ struct IopadmapPass : public Pass {
...
+			module_queue(design, module, modules_sorted, modules_processed);
+
+		for (auto module : modules_sorted)
 		{
-			pool<SigBit> skip_wire_bits;
-			dict<Wire *, dict<int, pair<Cell *, IdString>>> rewrite_bits;
+			pool<SigBit> buf_bits;
+			SigMap sigmap(module);
+
+			// Collect explicitely-marked already-buffered SigBits.
```
Comment (ZirconiumX) [inline passes/techmap/iopadmap.cc]: `explicitely` -> `explicitly`

**Comment by mwkmwkmwk** [comment]
Note: this is not a 100% correct fix, it still lets some (convoluted) cases through and will insert a double buffer:

```
module passthru(input i, output o);
assign o = i;
endmodule;

module top(output o);
wire tmp;
OBUF obuf_i(.I(whatever), .O(tmp));
passthru passthru_i(.i(tmp), .o(o));
endmodule
```

**Comment by mithro** [comment]
@litghost
