### PR TITLE
verilog: save and restore overwritten macro arguments

### LINKED ISSUE #2867: Unexpected macro behavior
## Steps to reproduce the issue

`Pad.sv` contains two almost identical modules, the difference is that the vector indices use a `MIN` macro in one case, and the macro is manually expanded in the other case. Loading the Verilog produces warnings in the `MIN` case.
[testcase.zip](https://github.com/YosysHQ/yosys/files/6819463/testcase.zip)

The problem is reproducible with:

`$ yosys -q -p "read_verilog -sv Pad.sv"`

## Expected behavior

No warnings.

## Actual behavior

Displays:

```
Pad.sv:6: Warning: Range [63:0] select out of bounds on signal `\y': Setting 63 MSB bits to undef.
Pad.sv:6: Warning: Ignoring assignment to constant bits:
    old assignment: { 63'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx \y } = { 63'000000000000000000000000000000000000000000000000000000000000000 \x }
    new assignment: \y = \x.
```

### PR DESCRIPTION
**Pull request by zachjs**
Fixes #2867

### CODE REVIEW

File: frontends/verilog/preproc.cc [hunk 1]
```diff
@@ -334,6 +335,11 @@ define_map_t::add(const std::string &name, const std::string &txt, const arg_map
 	defines[name] = std::unique_ptr<define_body_t>(new define_body_t(txt, args));
 }
 
+void define_map_t::add(const std::string &name, const define_body_t &body)
+{
+	defines[name] = std::unique_ptr<define_body_t>(new define_body_t(body));
```
Comment (mwkmwkmwk) [inline frontends/verilog/preproc.cc:340]: this looks like a job for `make_unique`

Comment (zachjs) [reply frontends/verilog/preproc.cc:340]: I was thinking the same thing, but unfortunately, `make_unique` was introduced in C++14.

File: frontends/verilog/preproc.cc [hunk 2]
```diff
@@ -495,6 +511,10 @@ static bool try_expand_macro(define_map_t &defines, std::string &tok)
 			args.push_back(arg);
 		}
 		for (const auto &pr : body->args.get_vals(name, args)) {
+			if (const define_body_t *existing = defines.find(pr.first)) {
+				macro_arg_stack.push({pr.first, *existing});
+				insert_input("`__restore_macro_arg");
```
Comment (mwkmwkmwk) [inline frontends/verilog/preproc.cc:516]: this needs armoring with spaces, otherwise:

```
module top(...);

`define add(x) x +

input [3:0] A;
output [3:0] B;
assign B = `add(`add(3)A)A;

endmodule
```

-->

```
-- Verilog code after preprocessor --
`file_push "t.v"
module top(...);



input [3:0] A;
output [3:0] B;
assign B = 3 +`__restore_macro_argA +A;

endmodule

`file_pop
-- END OF DUMP --
```

This, of course, blows up.

**Review by mwkmwkmwk — CHANGES_REQUESTED** [review]
(see inline comment)

File: frontends/verilog/preproc.cc (hunk 1 above)
Comment (mwkmwkmwk) [reply frontends/verilog/preproc.cc:340]: ... okay, nevermind then

File: frontends/verilog/preproc.cc (hunk 2 above)
Comment (zachjs) [reply frontends/verilog/preproc.cc]: Nice catch, thanks!

**Review by mwkmwkmwk — APPROVED** [review]
