### PR TITLE
Simplify and correct array slice assignment

### LINKED ISSUE #4064: Frontend/AST: signed assign to indexed part-select
### Version

Yosys 0.36+13 (git sha1 2858c33f6, clang 10.0.0-4ubuntu1 -fPIC -Os)

### On which OS did this happen?

Linux

### Reproduction Steps

The zip contains the source RTL, yosys output and a testbench.
[sign_part_assign.zip](https://github.com/YosysHQ/yosys/files/13638840/sign_part_assign.zip)

Execute the commands:
```
read_verilog sign_part_assign.v; proc; clean -purge; write_verilog -noattr sign_part_assign.yosys.v;
```
Compare the output `data_o` using the testbench or compare by inspection (its only a few lines to think through).

From inspecting the debug output from `read_verilog -debug` I expect the problem to be in the AST simplification step.

### Expected Behavior

Source RTL:
```verilog
always @(*) begin
    data_ref_o[offset_i+:4] = 4'b1111;
    data_o[offset_i+:4]     = 1'sb1;
end
```
The RHS of the second expression should be sign extended to match LHS width as per Sec 5.5.3 of IEEE Std 1364-2005 (Verilog 2005).
> The following are the steps for evaluating an assignment:
— Determine the size of the right-hand side by the standard assignment size determination rules (see 5.4).
— If needed, extend the size of the right-hand side, performing sign extension if, and only if, the type of the right-hand side is signed.

### Actual Behavior

The LHS extension to match RHS is done without considering the sign bit. So it produces essentially:
```verilog
always @(*) begin
    data_ref_o[offset_i+:4] = 4'b1111;
    data_o[offset_i+:4]     = 4'b0001; // unsigned from signed 1'sb1
end
```

### PR DESCRIPTION
**Pull request by daglem**
Simplify and correct AST for array slice assignment

Corrects sign extension of the right hand side, and hopefully
makes the code simpler to understand.

Fixes #4064

### CODE REVIEW

File: frontends/ast/simplify.cc [hunk 1]
```diff
@@ -2966,96 +2966,67 @@ bool AstNode::simplify(bool const_fold, int stage, int width_hint, bool sign_hin
...
+			shift_val = new AstNode(AST_NEG, shift_val);
 
-			AstNode *t;
-
-			t = mkconst_bits(std::vector<RTLIL::State>(result_width, State::S1), false);
-			t = new AstNode(AST_SHIFT, t, shamt->clone());
-			t = new AstNode(AST_ASSIGN_EQ, ref_mask->clone(), t);
-			newNode->children.push_back(t);
-
-			t = new AstNode(AST_BIT_AND, mkconst_bits(std::vector<RTLIL::State>(result_width, State::S1), false), children[1]->clone());
```
Comment (povik) [inline frontends/ast/simplify.cc:3050]: This is where the issue #4064 was, right? The rvalue is masked, but not sign-extended.

**Review by povik — APPROVED** [review]

**Comment by povik** [comment]
> and hopefully makes the code simpler to understand.

Much better now. Thanks!

File: frontends/ast/simplify.cc (hunk 1 above)
Comment (daglem) [reply frontends/ast/simplify.cc:3050]: Correct!
