### PR TITLE
fmt: Handle free-standing time arguments

### LINKED ISSUE #4018: Abort in kernel/fmt.cc:454 with "$display($time)" called
### Version

Yosys 0.34+55 (git sha1 672375ed0, clang 14.0.6 -fPIC -Os)

### On which OS did this happen?

Linux

### Reproduction Steps

Verilog file `top.v`:
```verilog
module top;
	initial $display($time);
endmodule
```
Run:
```
yosys -p "read_verilog top.v"
```

### Expected Behavior

Successfully finished Verilog frontend.

### Actual Behavior

```
-- Running command `read_verilog top.v' --

1. Executing Verilog-2005 frontend: top.v
Parsing Verilog input from `top.v' to AST representation.
Generating RTLIL representation for module `\top'.
ERROR: Abort in kernel/fmt.cc:454.
```

### PR DESCRIPTION
**Pull request by povik**
Fixes #4018

### CODE REVIEW

File: kernel/fmt.cc [hunk 1]
```diff
@@ -326,6 +326,16 @@ void Fmt::parse_verilog(const std::vector<VerilogFmtArg> &args, bool sformat_lik
 				break;
 			}
 
+			case VerilogFmtArg::TIME: {
+				FmtPart part = {};
+				part.type = FmtPart::TIME;
+				part.realtime = arg->realtime;
+				part.padding = ' ';
+				part.width = 20;
```
Comment (povik) [inline kernel/fmt.cc:334]: I copied what `$display("%t", $time)` does, not sure up to spec

Comment (whitequark) [reply kernel/fmt.cc:334]: I think that's not up to spec. I'm not sure who introduced this functionality--I think that was after I offered the fmt PR.

**Review by whitequark — APPROVED** [review]
It's probably OK to merge as-is.
