### PR TITLE
abc9: fix SCC issues

### LINKED ISSUE #2530: ABC9 flop bypass specify rules can cause combinational loops
This testcase has been minimised from a QuickLogic benchmark:
```verilog
module top(input WBs_CLK_i, _1_, _0_, output reg Rx_overflow_detected_o);
  wire rx_fifo_cntr_rst;
  assign rx_fifo_cntr_rst = _1_ | Rx_overflow_detected_o;
  always @(posedge WBs_CLK_i, posedge rx_fifo_cntr_rst)
    if (rx_fifo_cntr_rst) Rx_overflow_detected_o <= 1'h0;
    else Rx_overflow_detected_o <= _0_;
endmodule
```
which is a flop that asynchronously resets itself depending on its output.

## Expected behavior

If you take an ABC flow, such as `synth_ice40`, you get:
```
   Number of wires:                  5
   Number of wire bits:              5
   Number of public wires:           3
   Number of public wire bits:       3
   Number of memories:               0
   Number of memory bits:            0
   Number of processes:              0
   Number of cells:                  2
     SB_DFFR                         1
     SB_LUT4                         1
```

## Actual behavior

If you take an ABC9 flow, such as `synth_ice40`, you get:
```
2.41.9. Executing ABC9_OPS pass (helper functions for ABC9).
<suppressed ~2 debug messages>
ERROR: Assert `no_loops' failed in passes/techmap/abc9_ops.cc:758.
```

The cause of this is that near-universally flop cells have specify rules to produce an ABC9 flop bypass box that models the combinational path from a set/reset pin to the output. In this particular case, however, this models a combinational loop through the flop, which causes ABC9 to assert.

The reason I'm posting this as an issue is to come to a consensus on how to resolve this given the tradeoffs.

- We could consider this a combinational loop, which is forbidden in RTLIL, keep the specify rules, and possibly extract better results, since a longer critical path means more area reduction opportunities.
- We could remove the specify rules, which I have confirmed fixes the issue, but potentially regress result quality in the rare case that the critical path involves an asynchronous set/reset.
- I could attempt to fix this in ABC9, but with Eddie gone, it's going to be a bug that stays around for a long while, since I am very unfamiliar with the code there.

cc @daveshah1 (for iCE40/ECP5/Nexus), @pepijndevos (for Gowin), @mwkmwkmwk (for Xilinx)

### PR DESCRIPTION
**Pull request by eddiehung**
Fix #2530 -- specifically `(* abc9_box, lib_whitebox *)` cells that can be bypassed using a combinatorial-only box are no longer bypassed if they form part of a combinatorial loop (based on analysing connectivity only, not if it such a condition can be reached or will cause undefined behaviour -- such are the testcases from #2530 which occurs when the output of an async flop (which causes a bypass cell to capture async behaviour) fans back into to its async set/reset input).

Improve SCC handling overall. This is achieved by no longer marking combinatorial loops with `(* abc9_keep *)` and letting `write_xaiger` turn them into `inout`s -- this doesn't work if a box output drives a PO which cannot be turned into an `inout` -- so now use an explicit `$__ABC9_SCC_BREAKER` cell. 

Also tightens up some `abc9` testing.

CC: @Ravenslofty 

Please squash merge.

### CODE REVIEW

File: CODEOWNERS [hunk 1]
```diff
@@ -16,6 +16,7 @@ backends/cxxrtl/               @whitequark
 passes/cmds/bugpoint.cc        @whitequark
 passes/techmap/flowmap.cc      @whitequark
 passes/opt/opt_lut.cc          @whitequark
+passes/techmap/abc9*.cc        @eddiehung
```
Comment (Ravenslofty) [inline CODEOWNERS:19]: Might as well add yourself as code owner for `xaiger.cc` too.

File: passes/techmap/abc9_ops.cc [hunk 2]
```diff
@@ -1587,11 +1606,11 @@ struct Abc9OpsPass : public Pass {
...
 		log("        certain required times.\n");
 		log("\n");
-		log("    -mark_scc\n");
+		log("    -break_scc\n");
 		log("        for an arbitrarily chosen cell in each unique SCC of each selected module\n");
-		log("        (tagged with an (* abc9_scc_id = <int> *) attribute), temporarily mark all\n");
-		log("        wires driven by this cell's outputs with a (* keep *) attribute in order\n");
-		log("        to break the SCC. this temporary attribute will be removed on -reintegrate.\n");
+		log("        (tagged with an (* abc9_scc_id = <int> *) attribute), temporarily interrupt\n");
+		log("        all wires driven by this cell's outputs with a temporary $__ABC9_SCC_BREAKER\n");
```
Comment (Ravenslofty) [inline passes/techmap/abc9_ops.cc:1612]: Maybe a bit too nitpicky, but one "temporary" is probably enough.

**Review by Ravenslofty — APPROVED** [review]

**Comment by Ravenslofty** [comment]
Yep, looks good.

As for squash merging, you're still part of the YosysHQ org; might as well merge it yourself.

**Comment by sthornington** [comment]
Can confirm this fixes a 2530 combinational loop error I have been seeing since last fall some time.
