### PR TITLE
muxpack: fix wide Y port handling

### LINKED ISSUE #5734: muxpack crash on wide Y port
### Version

main

### On which OS did this happen?

Linux

### Reproduction Steps

```
module top(b);
  input b;
  wire ['h12 : 0] h = ~|b;
endmodule
```

`read_verilog garbage/muxpack-bug.v; proc; check -assert; muxpack`

see [here](https://github.com/YosysHQ/yosys/issues/5720#issuecomment-4024163983)

### Expected Behavior

muxpack gracefully handles whatever valid IR is thrown at it

### Actual Behavior

muxpack chokes on wide Y port on a `$logic_not` etc with `ERROR: Assert \`sig.size() == 1' failed in ./kernel/rtlil.h:2673.`

### PR DESCRIPTION
**Pull request by widlarizer**
Fixes #5734

### CODE REVIEW

File: passes/opt/muxpack.cc [hunk 1]
```diff
@@ -38,19 +38,25 @@ struct ExclusiveDatabase
 		pool<Cell*> reduce_or;
 		for (auto cell : module->cells()) {
 			if (cell->type == ID($eq)) {
+				SigSpec y_sig = sigmap(cell->getPort(ID::Y));
+				if (GetSize(y_sig) == 0)
+					continue;
```
Comment (gussmith23) [inline passes/opt/muxpack.cc:43]: out of curiosity, does this actually occur in practice? or are you just being safe here?

Comment (widlarizer) [reply passes/opt/muxpack.cc:43]: Purely avoiding a bad crash when later getting the y[0] SigBit. Could be an assert instead, but an error handling fix doesn't deserve the mental effort of pondering "is it possible that in some theoretical usage pattern of yosys something will emit a mux with zero width Y port"
