### PR TITLE
opt_expr: Optimize div/mod by const 1.

### LINKED ISSUE #2820: Unable to optimize `(a % 1) == 0`
## Steps to reproduce the issue

Running 
```verilog
module top(b, clk, rst, a);
  reg \initial  = 0;
  wire [31:0] \$1 ;
  wire [31:0] \$3 ;
  wire \$4 ;
  wire \$7 ;
  input [31:0] a;
  output [31:0] b;
  reg [31:0] b = 32'd0;
  reg [31:0] \b$next ;
  input clk;
  input rst;
  assign \$1  = a % 1'h1;
  assign \$4  = 1'h1 == 1'h0;
  assign \$3  = \$4  ? 32'd0 : \$1 ;
  assign \$7  = \$3  == 1'h0;
  always @(posedge clk)
    b <= \b$next ;
  always @* begin
    if (\initial ) begin end
    \b$next  = b;
    casez (\$7 )
      1'h1:
          \b$next  = a;
    endcase
    casez (rst)
      1'h1:
          \b$next  = 32'd0;
    endcase
  end
endmodule
```

through 

```
yosys test.v -p 'synth_ecp5'
```

(Tested on commit 55e8f5061af57bf25bd9e30528de8196c6eabe9e)

## Expected behavior

Only a handful of FFs is used:

```
   Number of cells:                 32
     TRELLIS_FF                     32
```

## Actual behavior

A insanely huge design is generated:

```
   Number of cells:               9583
     CCU2C                        1264
     L6MUX21                      1357
     LUT4                         4817
     PFUMX                        2113
     TRELLIS_FF                     32
```

## Additional information
The input verilog file is generated by the following nmigen code

```python
#!/usr/bin/env python3

from nmigen import *
from nmigen.back.verilog import convert

a = Signal(32)
b = Signal(32)
m = Module()

with m.If((a % 1) == 0):
   m.d.sync += b.eq(a)

print(convert(m, ports=(a,b), strip_internal_attrs=True))
```

### PR DESCRIPTION
**Pull request by mwkmwkmwk**
Turns out the code for div by a power of 2 is already almost capable of
optimizing this to a shift-by-0 or and-with-0, which will be further
folded into nothingness; let's beef it up to handle div by 1 as well.

Fixes #2820.

### CODE REVIEW

File: passes/opt/opt_expr.cc [hunk 1]
```diff
@@ -1648,7 +1648,7 @@ void replace_const_cells(RTLIL::Design *design, RTLIL::Module *module, bool cons
 					goto next_cell;
 				}
 
-				for (int i = 1; i < (b_signed ? sig_b.size()-1 : sig_b.size()); i++)
+				for (int i = 0; i < (b_signed ? sig_b.size()-1 : sig_b.size()); i++)
 					if (b_val == (1 << i))
```
Comment (mwkmwkmwk) [inline passes/opt/opt_expr.cc:1652]: *sigh* no.
